name: Bercelli
favicon: null
layout_spectrum: 1
typography_spectrum: 0.60163
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#2dbbe9'
    - '#5f3695'
    - '#f0e548'
    - '#f174d4'
    - '#000000'
  brandStrength: 0.3125
  lightness: 0.5826408455614001
  saturation: 0.9270368947181851
  rhythmicContrast: 0.031214149668812752
purpose: []
